### ISSUE TITLE
保存日志到文件时报IOException

### ISSUE THREAD

**Issue by githubtongdu** [xiaoyaoyou1212/ViseLog#1]
生成的日志文件名如：/storage/sdcard/Log/debug_2017-06-28 03:54.log
创建文件时，会导致java.io.IOException: open failed: EINVAL (Invalid argument)

com.vise.log.inner.FileTree:line85
可以考虑将HH:mm中的":"替换为"-"
p.s.在模拟器（API 19）上

**Comment by xiaoyaoyou1212** [comment]
@githubtongdu 这个问题确实没注意到，谢谢建议，现在问题已在V1.1.1版本上修复。
